### ISSUE TITLE
Database syntax error during full-init

### ISSUE THREAD

**Issue by max-kamps** [tshatrov/ichiran#8] opened 2020-06-28 14:53 UTC
Hello
I was trying to initialize the database following the instructions in the README but got stuck at this part

```lisp
$ rlwrap sbcl --noinform --load /etc/default/quicklisp
* (ql:quickload :ichiran)
To load "ichiran":
  Load 1 ASDF system:
    ichiran
; Loading "ichiran"
.
;;; Checking for wide character support... WARNING: Lisp implementation doesn't use UTF-16, but accepts surrogate code points.
 yes, using code points.
..
;;; Checking for wide character support... WARNING: Lisp implementation doesn't use UTF-16, but accepts surrogate code points.
 yes, using code points.
;;; Building Closure with CHARACTER RUNES
.......
(:ICHIRAN)
* (ichiran/maintenance:full-init)
Initializing ichiran/dict...

debugger invoked on a CL-POSTGRES-ERROR:COLUMNS-ERROR in thread
#<THREAD "main thread" RUNNING {1000898083}>:
  Database error 42601: syntax error at or near "table"
QUERY: DROP TABLE IF EXISTS table

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit debugger, returning to top level.

(CL-POSTGRES::GET-ERROR #<SB-SYS:FD-STREAM for "socket 127.0.0.1:56920, peer: 127.0.0.1:5432" {1008725E13}>)
   source: (ERROR (CL-POSTGRES-ERROR::GET-ERROR-TYPE CODE) :CODE CODE :MESSAGE
                  (GET-FIELD #\M) :DETAIL (GET-FIELD #\D) :HINT (GET-FIELD #\H)
                  :CONTEXT (GET-FIELD #\W) ...)
0] 
*
```

Here's my settings.lisp:
Since the JMdict repository has been reorganized since the README was written I had to guess where the paths are supposed to point.
```lisp
(in-package #:ichiran/conn)

(defparameter *connection* '("jmdict" "postgres" "" "localhost"))

; (defparameter *connections* '((:old "jmdict_old" "postgres" "" "localhost")
;                               (:test "jmdict_test" "postgres" "" "localhost")))

(in-package #:ichiran/dict)

(defparameter *jmdict-path* #p"/home/.../JMdict_e")

(defparameter *jmdict-data* #p"/home/.../jmdictdb/jmdictdb/data")

(in-package #:ichiran/kanji)

(defparameter *kanjidic-path* #P"/home/.../kanjidic2.xml")
```

**Comment by tshatrov** [comment] 2020-06-29 11:46
First of all, I recommend using the existing database dumps rather than full-init, not only is this faster but I usually have to add a lot of "errata" to make each new release pass the tests, because various changes in JMdict tend to break the segmenter or something else.

The bug might be a Postmodern regression. Namely `(SQL (:DROP-TABLE :IF-EXISTS TABLE))` expands to literally `"DROP TABLE IF EXISTS table"` which it shouldn't. I'll try to figure out when did this change.

**Comment by tshatrov** [comment] 2020-06-29 12:13
I filed a bug to postmodern. postmodern commit 08e548e316954970f9080aaa853591dd9b9f7148 is the latest one that still works.

**Comment by tshatrov** [comment] 2020-06-29 18:47
I have committed a workaround that should fix this issue.

**Closed by tshatrov** 2020-06-29 18:47 UTC
